### ISSUE TITLE
template drawLinesAndMarkersLegend misleading doc

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#115]
the 
```python
import vcs
x=vcs.init()
t=vcs.createtemplate()
t.drawLinesAndMarkersLegend(x,["red","blue","green"], ["solid","dash","dot"],[1,4,8],["blue","green","red"], ["cross","square","dot"],[3,4,5],["sample A","type B","thing C"],True)
```
fails
the `bg=True` keyword seems to make it fail (i think it's because was rendered previously)

**Comment by embrown** [comment]
@doutriaux1 Which version of the docs is this from? My current version, the doc has this example 
(The tedious declaration of lists is because the pdf formatting looks bad if those code examples go over 80 characters to a line):
```python
>>> x = vcs.init()
>>> t = vcs.createtemplate()
>>> l_colors=["red","blue","green"]
>>> l_types=["solid","dash","dot"]
>>> l_widths=[1,4,8]
>>> m_colors=["blue","green","red"]
>>> m_types=["cross","square","dot"]
>>> m_sizes=[3,4,5]
>>> strings=["sample A","type B","thing C"]
>>> scratch=[True,False,True]
>>> t.drawLinesAndMarkersLegend(x, l_colors, l_types, l_widths,
...     m_colors, m_types, m_sizes, strings, scratch)
>>> x.png("sample")
```
My [report](https://github.com/embrown/vcs/blob/more_more_documentation/docs/doctest_info/markdown/template.md) doesn't indicate that there was an error with that test, so I think this issue will be resolved as soon as https://github.com/UV-CDAT/vcs/pull/114 is reviewed and merged.

**Comment by doutriaux1** [comment]
good. @chaosphere2112 is reviewing this right now.
