### ISSUE TITLE
doc strings PR introduced bug in test suite

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/vcs#136]
Among others the following tests have been broken by @chaosphere2112 #131 
```
test_vcs_user_passed_date.py
```
latitude labels are gone
![test_vcs_user_passed_date](https://cloud.githubusercontent.com/assets/2781425/23486936/d4d544d8-fe97-11e6-9af3-e82dac0710fc.png)

**Comment by chaosphere2112** [comment]
@doutriaux1 What latitude labels are gone?

## 2.8 clean install:
![2 8_raw](https://cloud.githubusercontent.com/assets/718512/23487564/ce4c90b8-fe9b-11e6-824c-b7a013189bae.png)


## 2.8 with master branch of VCS:

![2 8_vcs_master](https://cloud.githubusercontent.com/assets/718512/23487563/cb13d80c-fe9b-11e6-8343-91a0f97f5663.png)

**Comment by chaosphere2112** [comment]
Ah, nevermind; looks like `ipython` opened in the old environment. I see now, and will hunt this down.

**Comment by chaosphere2112** [comment]
Got it.

[This line](https://github.com/UV-CDAT/vcs/blob/4268809dcd984db1372f79ff1cb6cb170f184653/vcs/utils.py#L2240)  in creategraphicsmethod()

```
elif gtype in ['boxfill', 'Gfb']:
        func = vcs.createboxfill
```

used to read

```
elif gtype in ['boxfill', 'default']:
        func = vcs.createboxfill
```

When it is that way, the desired behavior happens. This is almost definitely a bizarre bug internal to VCS, since the rest of the graphics methods all use "Gfm" or their proper graphics method names. I'll dig more into it tomorrow.
