### ISSUE TITLE
VCS PDF filesize is much larger than what you would get from MPL

### ISSUE THREAD

**Issue by aashish24** [UV-CDAT/vcs#33]

**Comment by durack1** [comment]
@aashish24 this is likely due to the characters as glyphs issue that we discussed at depth in UV-CDAT/uvcdat#1992, UV-CDAT/uvcdat#1537 and [UV-CDAT/uvcdat#1527](https://github.com/UV-CDAT/uvcdat/issues/1527#issuecomment-139002911)

**Comment by danlipsa** [comment]
The PDF file size difference is small now because PDFs are compressed as they are in matplotlib. For the script patterns.py the pdf file size increases from 2.3 to 3.7 MB. Attached are the python and pdf files.
[patterns_index_10_mpl.pdf](https://github.com/UV-CDAT/vcs/files/709224/patterns_index_10_mpl.pdf)
[patterns_index_10.pdf](https://github.com/UV-CDAT/vcs/files/709225/patterns_index_10.pdf)
